address comments

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -1,4 +1,4 @@
-name: "Create a tag"
+name: "Create a release"
 
 on:
   workflow_call:
@@ -12,10 +12,6 @@ on:
         description: "Tag for new version (v1.23.4)"
         required: true
         type: string
-      create_release:
-        description: "Create release and set as latest"
-        type: boolean
-        default: true
       base_tag:
         description: "Base tag to generate commit list for release notes"
         required: false
@@ -27,8 +23,8 @@ on:
         required: true
 
 jobs:
-  create-tag:
-    name: "Create a tag"
+  create-release:
+    name: "Create a release"
     runs-on: ubuntu-latest
 
     steps:
@@ -51,56 +47,38 @@ jobs:
           fetch-tags: true
           submodules: true
 
-      - name: Set up Github credentials
-        run: |
-          git config --local user.name 'Temporal Data'
-          git config --local user.email 'commander-data@temporal.io'
-
-      - name: Prepare new version string
-        id: new_version
-        env:
-          TAG: ${{ github.event.inputs.tag }}
-        run: |
-          if [[ "${TAG}" =~ ^v.* ]]; then
-              echo "tag=${TAG}" >> "$GITHUB_OUTPUT"
-          else
-              echo "tag=v${TAG}" >> "$GITHUB_OUTPUT"
-          fi
-
       - name: Validate input
         env:
           REF: ${{ github.event.inputs.ref }}
-          TAG: ${{ steps.new_version.outputs.tag }}
-          CREATE_RELEASE: ${{ github.event.inputs.create_release }}
+          TAG: ${{ github.event.inputs.tag }}
           BASE_TAG: ${{ github.event.inputs.base_tag }}
         run: |
+          if ! [[ "${TAG}" =~ ^v.* ]]; then
+            echo "::error::Tag is not prefixed with 'v'"
+            exit 1
+          fi
+
           if [[ -n "$(git tag -l "$TAG")" && "$(git rev-parse "$TAG")" != "$(git rev-parse HEAD)" ]]; then
             echo "::error::Tag already exists and it doesn't reference $REF"
             exit 1
           fi
 
-          if [[ "$CREATE_RELEASE" == "true" ]]; then
-            if [[ -z "$BASE_TAG" || -z "$(git tag -l "$BASE_TAG")" ]]; then
-              echo "::error::Base tag not specified or does not exist"
-              exit 1
-            fi
+          if [[ -z "$BASE_TAG" || -z "$(git tag -l "$BASE_TAG")" ]]; then
+            echo "::error::Base tag not specified or does not exist"
+            exit 1
           fi
 
-      - name: Create and push tag
-        env:
-          TAG: ${{ steps.new_version.outputs.tag }}
+      - name: Set up Github credentials
         run: |
-          if [[ -z "$(git tag -l "$TAG")" ]]; then
-            git tag "$TAG"
-            git push origin "$TAG"
-          fi
+          git config --local user.name 'Temporal Data'
+          git config --local user.email 'commander-data@temporal.io'
 
       - name: Create release
-        if: ${{ github.event.inputs.create_release == true || github.event.inputs.create_release == 'true' }}
         env:
           GH_TOKEN: ${{ steps.generate_token.outputs.token }}
-          TAG: ${{ steps.new_version.outputs.tag }}
+          REF: ${{ github.event.inputs.ref }}
+          TAG: ${{ github.event.inputs.tag }}
           BASE_TAG: ${{ github.event.inputs.base_tag }}
         run: |
           gh repo set-default ${{ github.repository }}
-          gh release create "$TAG" --verify-tag --latest --generate-notes --notes-start-tag "$BASE_TAG"
+          gh release create "$TAG" --target "$REF" --latest --generate-notes --notes-start-tag "$BASE_TAG"
