address comments

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -1,4 +1,4 @@
-name: "Create a release"
+name: "Create release"
 
 on:
   workflow_call:
@@ -7,9 +7,12 @@ on:
         description: "Ref to be tagged"
         required: true
         type: string
-        default: master
       tag:
         description: "Tag for new version (v1.23.4)"
+        required: true
+        type: string
+      api_commit_sha:
+        description: "api repo commit sha"
         required: true
         type: string
       base_tag:
@@ -24,7 +27,7 @@ on:
 
 jobs:
   create-release:
-    name: "Create a release"
+    name: "Create release"
     runs-on: ubuntu-latest
 
     steps:
@@ -40,7 +43,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           repository: temporalio/api-go
-          ref: ${{ github.event.inputs.ref }}
+          ref: ${{ inputs.ref }}
           token: ${{ steps.generate_token.outputs.token }}
           persist-credentials: true
           fetch-depth: 0
@@ -49,22 +52,29 @@ jobs:
 
       - name: Validate input
         env:
-          REF: ${{ github.event.inputs.ref }}
-          TAG: ${{ github.event.inputs.tag }}
-          BASE_TAG: ${{ github.event.inputs.base_tag }}
+          REF: ${{ inputs.ref }}
+          TAG: ${{ inputs.tag }}
+          API_COMMIT_SHA: ${{ inputs.api_commit_sha }}
+          BASE_TAG: ${{ inputs.base_tag }}
         run: |
           if ! [[ "${TAG}" =~ ^v.* ]]; then
             echo "::error::Tag is not prefixed with 'v'"
             exit 1
           fi
 
-          if [[ -n "$(git tag -l "$TAG")" && "$(git rev-parse "$TAG")" != "$(git rev-parse HEAD)" ]]; then
-            echo "::error::Tag already exists and it doesn't reference $REF"
+          if [[ -n "$(git tag -l "$TAG")" ]]; then
+            echo "::error::Tag already exists"
             exit 1
           fi
 
           if [[ -z "$BASE_TAG" || -z "$(git tag -l "$BASE_TAG")" ]]; then
             echo "::error::Base tag not specified or does not exist"
+            exit 1
+          fi
+
+          API_GO_API_COMMIT_SHA=$(git rev-parse HEAD:proto/api)
+          if [[ "${API_GO_API_COMMIT_SHA}" != "${API_COMMIT_SHA}" ]]; then
+            echo "::error::api-go ref ${API_GO_COMMIT_SHA} does not reference api ref ${API_COMMIT_SHA}."
             exit 1
           fi
 
@@ -76,9 +86,10 @@ jobs:
       - name: Create release
         env:
           GH_TOKEN: ${{ steps.generate_token.outputs.token }}
-          REF: ${{ github.event.inputs.ref }}
-          TAG: ${{ github.event.inputs.tag }}
-          BASE_TAG: ${{ github.event.inputs.base_tag }}
+          REF: ${{ inputs.ref }}
+          TAG: ${{ inputs.tag }}
+          API_COMMIT_SHA: ${{ inputs.api_commit_sha }}
+          BASE_TAG: ${{ inputs.base_tag }}
         run: |
-          gh repo set-default ${{ github.repository }}
-          gh release create "$TAG" --target "$REF" --latest --generate-notes --notes-start-tag "$BASE_TAG"
+          gh repo set-default temporalio/api-go
+          gh release create "$TAG" --title "${TAG}-${API_COMMIT_SHA}" --target "$REF" --latest --generate-notes --notes-start-tag "$BASE_TAG" --draft
